"""Initial migration

Revision ID: cfe185efb922
Revises: 
Create Date: 2024-12-17 10:47:08.266667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cfe185efb922'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('secondtitle', sa.String(length=225), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('topimg', sa.String(length=225), nullable=True),
    sa.Column('otherimgs', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works')
    # ### end Alembic commands ###
